### ISSUE TITLE
Feature request: open in new tab

### ISSUE THREAD

**Issue by pchampin** [hartag/keynav#7]
I love this add-on :)
I would love it even more if it allowed me to open the targeted folder in a new tab.
Ideally, this would be possible by pressing CTRL+ENTER (for example) instead of ENTER...

As an alternative, having a configuration option to always open in a new tab instead of the current tab, would be fine by me.

**Comment by hartag** [comment]
I've pushed a commit to the repository that basically does this, but it requires Thunderbird 121.0 or later. Version 121.0 is the current beta version of Thunderbird. I can't make it work in earlier versions.

**Comment by pchampin** [comment]
Thanks a lot. I'll wait until TB 121.0 is released :)
